WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
WHENEVER OSERROR  EXIT FAILURE ROLLBACK;

spool 20190401_df_move_cars_entrance.log

set feedback off
set define off


DECLARE
r_layout_config hls_doc_layout_config%rowtype;
r_layout_config_lov hls_doc_layout_config_lov%rowtype;
v_layout_config_id number;
BEGIN
SYS_LOAD_HLS_DOC_LAYOUT_PKG.delete_layout('DF_MOVE_CARS_ENTRANCE');
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout(P_LAYOUT_CODE=>'DF_MOVE_CARS_ENTRANCE',P_DESCRIPTION=>'车辆移库(DF)',P_DOCUMENT_CATEGORY=>'CONTRACT',P_ORDER_SEQ=>125,P_ENABLED_FLAG=>'Y',P_USER_ID=>1);
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_tab(P_LAYOUT_CODE=>'DF_MOVE_CARS_ENTRANCE',P_TAB_CODE=>'F_QUERY',P_TAB_TYPE=>'FORM',P_TAB_DESC=>'查询条件',P_ENABLED_FLAG=>'Y',P_PARENT_TAB_CODE=>null,P_TAB_SEQ=>10,P_TAB_GROUP=>null,P_BASE_TABLE=>null,P_BASE_TABLE_PK=>null,P_BASE_TABLE_FIELD=>null,P_QUERY_SOURCE=>null,P_PARENT_TABLE=>null,P_CONFIGURABLE=>'Y',P_ROW_COUNT=>2,P_COLUMN_COUNT=>4,P_LABEL_WIDTH=>120,P_FIELD_WIDTH=>150,P_MARGIN_TOP=>3,P_MARGIN_HEIGHT=>100,P_MARGIN_WIDTH=>70,P_SHOW_BOX=>'Y',P_BOX_WIDTH=>1112,P_TREE_CODE=>null,P_TREE_LEVEL=>1,P_REPEAT_OBJECT=>null,P_REF_TAB_CODE=>null,P_TAB_REF_SCREEN=>null,P_REPEAT_BINDERTARGET_FLAG=>'N',P_ROOT_TREE_CODE=>null,P_SETUP_HEIGHT=>'MARGIN_HEIGHT',P_HEIGHT=>null,P_SETUP_WIDTH=>'MARGIN_WIDTH',P_WIDTH=>null,P_PARENT_LOADED_OBJECT=>null,P_ATTACHMENT_TAB_GROUP=>null,P_REPEAT_BINDNAME_OBJECT=>null,P_USER_ID=>1,P_QUERY_ONLY=>'N',P_REF_V01=>null,P_REF_V02=>null,P_REF_V03=>null,P_REF_V04=>null,P_REF_V05=>null,P_FETCHALL =>'N',P_QUERY_TAB_CODE =>null,P_FIELDWIDTH =>null,P_FIELDHEIGHT =>null,P_CHECK_BEFORE_DELETE_BM =>null,P_CHECK_AFTER_SAVE_BM =>null,P_SWITCHCARD_VALUE=>null,P_RECREATE_DS_FLAG=>'N');
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_tab(P_LAYOUT_CODE=>'DF_MOVE_CARS_ENTRANCE',P_TAB_CODE=>'G_CONFIRM',P_TAB_TYPE=>'GRID',P_TAB_DESC=>null,P_ENABLED_FLAG=>'Y',P_PARENT_TAB_CODE=>'T_NUM_1',P_TAB_SEQ=>25,P_TAB_GROUP=>null,P_BASE_TABLE=>'CON_CONTRACT_DF_CAR_INFO',P_BASE_TABLE_PK=>'CAR_INFO_ID',P_BASE_TABLE_FIELD=>null,P_QUERY_SOURCE=>'con_contract_df_car_info_v',P_PARENT_TABLE=>null,P_CONFIGURABLE=>'Y',P_ROW_COUNT=>0,P_COLUMN_COUNT=>4,P_LABEL_WIDTH=>120,P_FIELD_WIDTH=>150,P_MARGIN_TOP=>3,P_MARGIN_HEIGHT=>260,P_MARGIN_WIDTH=>75,P_SHOW_BOX=>'Y',P_BOX_WIDTH=>1112,P_TREE_CODE=>null,P_TREE_LEVEL=>2,P_REPEAT_OBJECT=>null,P_REF_TAB_CODE=>null,P_TAB_REF_SCREEN=>null,P_REPEAT_BINDERTARGET_FLAG=>'N',P_ROOT_TREE_CODE=>null,P_SETUP_HEIGHT=>'MARGIN_HEIGHT',P_HEIGHT=>null,P_SETUP_WIDTH=>'MARGIN_WIDTH',P_WIDTH=>null,P_PARENT_LOADED_OBJECT=>null,P_ATTACHMENT_TAB_GROUP=>null,P_REPEAT_BINDNAME_OBJECT=>null,P_USER_ID=>1,P_QUERY_ONLY=>'N',P_REF_V01=>null,P_REF_V02=>null,P_REF_V03=>null,P_REF_V04=>null,P_REF_V05=>null,P_FETCHALL =>'N',P_QUERY_TAB_CODE =>'F_QUERY',P_FIELDWIDTH =>null,P_FIELDHEIGHT =>null,P_CHECK_BEFORE_DELETE_BM =>null,P_CHECK_AFTER_SAVE_BM =>null,P_SWITCHCARD_VALUE=>null,P_RECREATE_DS_FLAG=>'N');
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_tab(P_LAYOUT_CODE=>'DF_MOVE_CARS_ENTRANCE',P_TAB_CODE=>'G_WILLMOVE',P_TAB_TYPE=>'GRID',P_TAB_DESC=>null,P_ENABLED_FLAG=>'Y',P_PARENT_TAB_CODE=>'T_NUM_2',P_TAB_SEQ=>40,P_TAB_GROUP=>null,P_BASE_TABLE=>'CON_CONTRACT_DF_CAR_INFO',P_BASE_TABLE_PK=>'CAR_INFO_ID',P_BASE_TABLE_FIELD=>null,P_QUERY_SOURCE=>'con_contract_df_car_info_v',P_PARENT_TABLE=>null,P_CONFIGURABLE=>'Y',P_ROW_COUNT=>0,P_COLUMN_COUNT=>4,P_LABEL_WIDTH=>120,P_FIELD_WIDTH=>150,P_MARGIN_TOP=>3,P_MARGIN_HEIGHT=>260,P_MARGIN_WIDTH=>75,P_SHOW_BOX=>'Y',P_BOX_WIDTH=>1112,P_TREE_CODE=>null,P_TREE_LEVEL=>2,P_REPEAT_OBJECT=>null,P_REF_TAB_CODE=>null,P_TAB_REF_SCREEN=>null,P_REPEAT_BINDERTARGET_FLAG=>'N',P_ROOT_TREE_CODE=>null,P_SETUP_HEIGHT=>'MARGIN_HEIGHT',P_HEIGHT=>null,P_SETUP_WIDTH=>'MARGIN_WIDTH',P_WIDTH=>null,P_PARENT_LOADED_OBJECT=>null,P_ATTACHMENT_TAB_GROUP=>null,P_REPEAT_BINDNAME_OBJECT=>null,P_USER_ID=>1,P_QUERY_ONLY=>'N',P_REF_V01=>null,P_REF_V02=>null,P_REF_V03=>null,P_REF_V04=>null,P_REF_V05=>null,P_FETCHALL =>'N',P_QUERY_TAB_CODE =>'F_QUERY',P_FIELDWIDTH =>null,P_FIELDHEIGHT =>null,P_CHECK_BEFORE_DELETE_BM =>null,P_CHECK_AFTER_SAVE_BM =>null,P_SWITCHCARD_VALUE=>null,P_RECREATE_DS_FLAG=>'N');
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_tab(P_LAYOUT_CODE=>'DF_MOVE_CARS_ENTRANCE',P_TAB_CODE=>'T_NUM_1',P_TAB_TYPE=>'TAB',P_TAB_DESC=>'待移库',P_ENABLED_FLAG=>'Y',P_PARENT_TAB_CODE=>null,P_TAB_SEQ=>20,P_TAB_GROUP=>10,P_BASE_TABLE=>null,P_BASE_TABLE_PK=>null,P_BASE_TABLE_FIELD=>null,P_QUERY_SOURCE=>null,P_PARENT_TABLE=>null,P_CONFIGURABLE=>'Y',P_ROW_COUNT=>0,P_COLUMN_COUNT=>4,P_LABEL_WIDTH=>120,P_FIELD_WIDTH=>150,P_MARGIN_TOP=>3,P_MARGIN_HEIGHT=>200,P_MARGIN_WIDTH=>50,P_SHOW_BOX=>'Y',P_BOX_WIDTH=>1112,P_TREE_CODE=>null,P_TREE_LEVEL=>1,P_REPEAT_OBJECT=>null,P_REF_TAB_CODE=>null,P_TAB_REF_SCREEN=>null,P_REPEAT_BINDERTARGET_FLAG=>'N',P_ROOT_TREE_CODE=>null,P_SETUP_HEIGHT=>'MARGIN_HEIGHT',P_HEIGHT=>null,P_SETUP_WIDTH=>'MARGIN_WIDTH',P_WIDTH=>null,P_PARENT_LOADED_OBJECT=>null,P_ATTACHMENT_TAB_GROUP=>null,P_REPEAT_BINDNAME_OBJECT=>null,P_USER_ID=>1,P_QUERY_ONLY=>'N',P_REF_V01=>null,P_REF_V02=>null,P_REF_V03=>null,P_REF_V04=>null,P_REF_V05=>null,P_FETCHALL =>'N',P_QUERY_TAB_CODE =>null,P_FIELDWIDTH =>null,P_FIELDHEIGHT =>null,P_CHECK_BEFORE_DELETE_BM =>null,P_CHECK_AFTER_SAVE_BM =>null,P_SWITCHCARD_VALUE=>null,P_RECREATE_DS_FLAG=>'N');
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_tab(P_LAYOUT_CODE=>'DF_MOVE_CARS_ENTRANCE',P_TAB_CODE=>'T_NUM_2',P_TAB_TYPE=>'TAB',P_TAB_DESC=>'待提交',P_ENABLED_FLAG=>'Y',P_PARENT_TAB_CODE=>null,P_TAB_SEQ=>30,P_TAB_GROUP=>10,P_BASE_TABLE=>null,P_BASE_TABLE_PK=>null,P_BASE_TABLE_FIELD=>null,P_QUERY_SOURCE=>null,P_PARENT_TABLE=>null,P_CONFIGURABLE=>'Y',P_ROW_COUNT=>0,P_COLUMN_COUNT=>4,P_LABEL_WIDTH=>120,P_FIELD_WIDTH=>150,P_MARGIN_TOP=>3,P_MARGIN_HEIGHT=>200,P_MARGIN_WIDTH=>50,P_SHOW_BOX=>'Y',P_BOX_WIDTH=>1112,P_TREE_CODE=>null,P_TREE_LEVEL=>1,P_REPEAT_OBJECT=>null,P_REF_TAB_CODE=>null,P_TAB_REF_SCREEN=>null,P_REPEAT_BINDERTARGET_FLAG=>'N',P_ROOT_TREE_CODE=>null,P_SETUP_HEIGHT=>'MARGIN_HEIGHT',P_HEIGHT=>null,P_SETUP_WIDTH=>'MARGIN_WIDTH',P_WIDTH=>null,P_PARENT_LOADED_OBJECT=>null,P_ATTACHMENT_TAB_GROUP=>null,P_REPEAT_BINDNAME_OBJECT=>null,P_USER_ID=>1,P_QUERY_ONLY=>'N',P_REF_V01=>null,P_REF_V02=>null,P_REF_V03=>null,P_REF_V04=>null,P_REF_V05=>null,P_FETCHALL =>'N',P_QUERY_TAB_CODE =>null,P_FIELDWIDTH =>null,P_FIELDHEIGHT =>null,P_CHECK_BEFORE_DELETE_BM =>null,P_CHECK_AFTER_SAVE_BM =>null,P_SWITCHCARD_VALUE=>null,P_RECREATE_DS_FLAG=>'N');
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_ENTRANCE';r_layout_config.tab_code:='F_QUERY' ;r_layout_config.column_name:='CAR_STATUS';r_layout_config.data_type:='VARCHAR2';r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=30;r_layout_config.prompt:='车辆状态';r_layout_config.input_mode:='OPTION';r_layout_config.validation_type:='COMBOBOX' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=null;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:='select S.code_value value_code,S.code_value_name  VALUE_NAME
  from sys_code_values_v s
 where s.code = ''KR_CAR_STATUS''
   and s.code_enabled_flag = ''Y''
   AND S.code_value_enabled_flag = ''Y''
   ORDER BY S.order_seq';r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_ENTRANCE';r_layout_config.tab_code:='F_QUERY' ;r_layout_config.column_name:='CONTRACT_NUMBER';r_layout_config.data_type:='VARCHAR2';r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=20;r_layout_config.prompt:='合同编号';r_layout_config.input_mode:='OPTION';r_layout_config.validation_type:='TEXTFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=null;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_ENTRANCE';r_layout_config.tab_code:='F_QUERY' ;r_layout_config.column_name:='CONTRACT_STATUS';r_layout_config.data_type:='VARCHAR2';r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=25;r_layout_config.prompt:='合同状态';r_layout_config.input_mode:='OPTION';r_layout_config.validation_type:='COMBOBOX' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=null;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:='select s.code_value value_code,s.code_value_name  value_name
  from sys_code_values_v s
 where s.code = ''CON660_CONTRACT_STATUS''
   and s.code_enabled_flag = ''Y''
   AND s.code_value_enabled_flag = ''Y''
   ORDER BY s.order_seq';r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_ENTRANCE';r_layout_config.tab_code:='F_QUERY' ;r_layout_config.column_name:='ITEM_FRAME_NUMBER';r_layout_config.data_type:='VARCHAR2';r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=22;r_layout_config.prompt:='VIN码';r_layout_config.input_mode:='OPTION';r_layout_config.validation_type:='TEXTFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=null;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_ENTRANCE';r_layout_config.tab_code:='F_QUERY' ;r_layout_config.column_name:='PROJECT_NUMBER';r_layout_config.data_type:='VARCHAR2';r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=10;r_layout_config.prompt:='申请编号';r_layout_config.input_mode:='OPTION';r_layout_config.validation_type:='TEXTFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=null;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_ENTRANCE';r_layout_config.tab_code:='F_QUERY' ;r_layout_config.column_name:='SON_CODE';r_layout_config.data_type:='VARCHAR2';r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=21;r_layout_config.prompt:='SON号';r_layout_config.input_mode:='OPTION';r_layout_config.validation_type:='TEXTFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=null;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_ENTRANCE';r_layout_config.tab_code:='G_CONFIRM' ;r_layout_config.column_name:='AGENT_INVENTORY_ID';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=80;r_layout_config.prompt:='库点信息';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='LOV_D' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=120;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:='BP_ID';r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:='select inventory_id value_code,
       inventory_name value_name,
       address,
       inventory_address_level_n
from inventory_info_lv
where bp_id =${@bp_id}';r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config_lov.lov_config_id := hls_util_pkg.format_number(hls_doc_layout_config_lov_s.nextval);r_layout_config_lov.config_id := hls_util_pkg.format_number(v_layout_config_id);r_layout_config_lov.lov_col_for_query := 'N';r_layout_config_lov.lov_col_for_display := 'N';r_layout_config_lov.lov_col_display_width := 120;r_layout_config_lov.lov_data_type := 'NUMBER';r_layout_config_lov.created_by := 1;r_layout_config_lov.creation_date := to_date('2019-04-01','yyyy-mm-dd');r_layout_config_lov.last_update_date := to_date('2019-04-01','yyyy-mm-dd');r_layout_config_lov.last_updated_by  := 1;r_layout_config_lov.lov_col_prompt := 'VALUE_CODE';r_layout_config_lov.lov_col_sequence := 1;r_layout_config_lov.lov_col_name := 'VALUE_CODE';
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config_lov(r_layout_config_lov);
r_layout_config_lov.lov_config_id := hls_util_pkg.format_number(hls_doc_layout_config_lov_s.nextval);r_layout_config_lov.config_id := hls_util_pkg.format_number(v_layout_config_id);r_layout_config_lov.lov_col_for_query := 'Y';r_layout_config_lov.lov_col_for_display := 'Y';r_layout_config_lov.lov_col_display_width := 120;r_layout_config_lov.lov_data_type := 'VARCHAR2';r_layout_config_lov.created_by := 1;r_layout_config_lov.creation_date := to_date('2019-04-01','yyyy-mm-dd');r_layout_config_lov.last_update_date := to_date('2019-04-01','yyyy-mm-dd');r_layout_config_lov.last_updated_by  := 1;r_layout_config_lov.lov_col_prompt := '库点名称';r_layout_config_lov.lov_col_sequence := 2;r_layout_config_lov.lov_col_name := 'VALUE_NAME';
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config_lov(r_layout_config_lov);
r_layout_config_lov.lov_config_id := hls_util_pkg.format_number(hls_doc_layout_config_lov_s.nextval);r_layout_config_lov.config_id := hls_util_pkg.format_number(v_layout_config_id);r_layout_config_lov.lov_col_for_query := 'Y';r_layout_config_lov.lov_col_for_display := 'Y';r_layout_config_lov.lov_col_display_width := 120;r_layout_config_lov.lov_data_type := 'VARCHAR2';r_layout_config_lov.created_by := 1;r_layout_config_lov.creation_date := to_date('2019-04-01','yyyy-mm-dd');r_layout_config_lov.last_update_date := to_date('2019-04-01','yyyy-mm-dd');r_layout_config_lov.last_updated_by  := 1;r_layout_config_lov.lov_col_prompt := '地址';r_layout_config_lov.lov_col_sequence := 3;r_layout_config_lov.lov_col_name := 'ADDRESS';
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config_lov(r_layout_config_lov);
r_layout_config_lov.lov_config_id := hls_util_pkg.format_number(hls_doc_layout_config_lov_s.nextval);r_layout_config_lov.config_id := hls_util_pkg.format_number(v_layout_config_id);r_layout_config_lov.lov_col_for_query := 'Y';r_layout_config_lov.lov_col_for_display := 'Y';r_layout_config_lov.lov_col_display_width := 120;r_layout_config_lov.lov_data_type := 'VARCHAR2';r_layout_config_lov.created_by := 1;r_layout_config_lov.creation_date := to_date('2019-04-01','yyyy-mm-dd');r_layout_config_lov.last_update_date := to_date('2019-04-01','yyyy-mm-dd');r_layout_config_lov.last_updated_by  := 1;r_layout_config_lov.lov_col_prompt := '库点级别';r_layout_config_lov.lov_col_sequence := 4;r_layout_config_lov.lov_col_name := 'INVENTORY_ADDRESS_LEVEL_N';
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config_lov(r_layout_config_lov);
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_ENTRANCE';r_layout_config.tab_code:='G_CONFIRM' ;r_layout_config.column_name:='BP_ID';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='N' ;r_layout_config.display_order:=5;r_layout_config.prompt:='经销商ID';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='TEXTFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=130;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config_lov.lov_config_id := hls_util_pkg.format_number(hls_doc_layout_config_lov_s.nextval);r_layout_config_lov.config_id := hls_util_pkg.format_number(v_layout_config_id);r_layout_config_lov.lov_col_for_query := 'Y';r_layout_config_lov.lov_col_for_display := 'Y';r_layout_config_lov.lov_col_display_width := 120;r_layout_config_lov.lov_data_type := 'VARCHAR2';r_layout_config_lov.created_by := 1;r_layout_config_lov.creation_date := to_date('2019-04-01','yyyy-mm-dd');r_layout_config_lov.last_update_date := to_date('2019-04-01','yyyy-mm-dd');r_layout_config_lov.last_updated_by  := 1;r_layout_config_lov.lov_col_prompt := 'VALUE_NAME';r_layout_config_lov.lov_col_sequence := 2;r_layout_config_lov.lov_col_name := 'VALUE_NAME';
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config_lov(r_layout_config_lov);
r_layout_config_lov.lov_config_id := hls_util_pkg.format_number(hls_doc_layout_config_lov_s.nextval);r_layout_config_lov.config_id := hls_util_pkg.format_number(v_layout_config_id);r_layout_config_lov.lov_col_for_query := 'Y';r_layout_config_lov.lov_col_for_display := 'Y';r_layout_config_lov.lov_col_display_width := 120;r_layout_config_lov.lov_data_type := 'VARCHAR2';r_layout_config_lov.created_by := 1;r_layout_config_lov.creation_date := to_date('2019-04-01','yyyy-mm-dd');r_layout_config_lov.last_update_date := to_date('2019-04-01','yyyy-mm-dd');r_layout_config_lov.last_updated_by  := 1;r_layout_config_lov.lov_col_prompt := 'BP_CODE';r_layout_config_lov.lov_col_sequence := 3;r_layout_config_lov.lov_col_name := 'BP_CODE';
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config_lov(r_layout_config_lov);
r_layout_config_lov.lov_config_id := hls_util_pkg.format_number(hls_doc_layout_config_lov_s.nextval);r_layout_config_lov.config_id := hls_util_pkg.format_number(v_layout_config_id);r_layout_config_lov.lov_col_for_query := 'Y';r_layout_config_lov.lov_col_for_display := 'Y';r_layout_config_lov.lov_col_display_width := 120;r_layout_config_lov.lov_data_type := 'NUMBER';r_layout_config_lov.created_by := 1;r_layout_config_lov.creation_date := to_date('2019-04-01','yyyy-mm-dd');r_layout_config_lov.last_update_date := to_date('2019-04-01','yyyy-mm-dd');r_layout_config_lov.last_updated_by  := 1;r_layout_config_lov.lov_col_prompt := 'VALUE_CODE';r_layout_config_lov.lov_col_sequence := 1;r_layout_config_lov.lov_col_name := 'VALUE_CODE';
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config_lov(r_layout_config_lov);
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_ENTRANCE';r_layout_config.tab_code:='G_CONFIRM' ;r_layout_config.column_name:='BP_NAME';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=6;r_layout_config.prompt:='经销商名称';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='TEXTFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=130;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_ENTRANCE';r_layout_config.tab_code:='G_CONFIRM' ;r_layout_config.column_name:='CAR_INFO_ID';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='N' ;r_layout_config.display_order:=null;r_layout_config.prompt:=null;r_layout_config.input_mode:=null;r_layout_config.validation_type:='TEXTFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=null;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_ENTRANCE';r_layout_config.tab_code:='G_CONFIRM' ;r_layout_config.column_name:='CAR_STATUS';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=90;r_layout_config.prompt:='车辆状态';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='COMBOBOX' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=120;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:='select S.code_value value_code,S.code_value_name  VALUE_NAME
  from sys_code_values_v s
 where s.code = ''KR_CAR_STATUS''
   and s.code_enabled_flag = ''Y''
   AND S.code_value_enabled_flag = ''Y''
   ORDER BY S.order_seq';r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_ENTRANCE';r_layout_config.tab_code:='G_CONFIRM' ;r_layout_config.column_name:='CONTRACT_NUMBER';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=15;r_layout_config.prompt:='合同编号';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='TEXTFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=130;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_ENTRANCE';r_layout_config.tab_code:='G_CONFIRM' ;r_layout_config.column_name:='CONTRACT_STATUS';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=100;r_layout_config.prompt:='合同状态';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='COMBOBOX' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=120;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:='select S.code_value value_code,S.code_value_name  VALUE_NAME
  from sys_code_values_v s
 where s.code = ''CON660_CONTRACT_STATUS''
   and s.code_enabled_flag = ''Y''
   AND S.code_value_enabled_flag = ''Y''
   ORDER BY S.order_seq';r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_ENTRANCE';r_layout_config.tab_code:='G_CONFIRM' ;r_layout_config.column_name:='ITEM_ENGINE_NUMBER';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=60;r_layout_config.prompt:='发动机号';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='TEXTFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=120;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_ENTRANCE';r_layout_config.tab_code:='G_CONFIRM' ;r_layout_config.column_name:='ITEM_FRAME_NUMBER';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=20;r_layout_config.prompt:='VIN码';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='TEXTFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=150;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_ENTRANCE';r_layout_config.tab_code:='G_CONFIRM' ;r_layout_config.column_name:='MODEL_CODE';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=30;r_layout_config.prompt:='车型代码';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='TEXTFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=130;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_ENTRANCE';r_layout_config.tab_code:='G_CONFIRM' ;r_layout_config.column_name:='MODEL_CODE_NAME';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=40;r_layout_config.prompt:='车型代码描述';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='TEXTFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=150;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_ENTRANCE';r_layout_config.tab_code:='G_CONFIRM' ;r_layout_config.column_name:='PROJECT_NUMBER';r_layout_config.data_type:='VARCHAR2';r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=10;r_layout_config.prompt:='申请编号';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='TEXTFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=130;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_ENTRANCE';r_layout_config.tab_code:='G_CONFIRM' ;r_layout_config.column_name:='QUALIFIED_NUMBER';r_layout_config.data_type:='VARCHAR2';r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=70;r_layout_config.prompt:='合格证号';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='TEXTFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=120;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_ENTRANCE';r_layout_config.tab_code:='G_CONFIRM' ;r_layout_config.column_name:='SON_CODE';r_layout_config.data_type:='VARCHAR2';r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=16;r_layout_config.prompt:='SON号';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='TEXTFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=130;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_ENTRANCE';r_layout_config.tab_code:='G_WILLMOVE' ;r_layout_config.column_name:='AGENT_INVENTORY_ID';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=80;r_layout_config.prompt:='库点信息';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='LOV_D' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=120;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:='BP_ID';r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:='select inventory_id value_code,
       inventory_name value_name,
       address,
       inventory_address_level_n
from inventory_info_lv
where bp_id =${@bp_id}';r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config_lov.lov_config_id := hls_util_pkg.format_number(hls_doc_layout_config_lov_s.nextval);r_layout_config_lov.config_id := hls_util_pkg.format_number(v_layout_config_id);r_layout_config_lov.lov_col_for_query := 'N';r_layout_config_lov.lov_col_for_display := 'N';r_layout_config_lov.lov_col_display_width := 120;r_layout_config_lov.lov_data_type := 'NUMBER';r_layout_config_lov.created_by := 1;r_layout_config_lov.creation_date := to_date('2019-04-01','yyyy-mm-dd');r_layout_config_lov.last_update_date := to_date('2019-04-01','yyyy-mm-dd');r_layout_config_lov.last_updated_by  := 1;r_layout_config_lov.lov_col_prompt := 'VALUE_CODE';r_layout_config_lov.lov_col_sequence := 1;r_layout_config_lov.lov_col_name := 'VALUE_CODE';
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config_lov(r_layout_config_lov);
r_layout_config_lov.lov_config_id := hls_util_pkg.format_number(hls_doc_layout_config_lov_s.nextval);r_layout_config_lov.config_id := hls_util_pkg.format_number(v_layout_config_id);r_layout_config_lov.lov_col_for_query := 'Y';r_layout_config_lov.lov_col_for_display := 'Y';r_layout_config_lov.lov_col_display_width := 120;r_layout_config_lov.lov_data_type := 'VARCHAR2';r_layout_config_lov.created_by := 1;r_layout_config_lov.creation_date := to_date('2019-04-01','yyyy-mm-dd');r_layout_config_lov.last_update_date := to_date('2019-04-01','yyyy-mm-dd');r_layout_config_lov.last_updated_by  := 1;r_layout_config_lov.lov_col_prompt := '库点名称';r_layout_config_lov.lov_col_sequence := 2;r_layout_config_lov.lov_col_name := 'VALUE_NAME';
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config_lov(r_layout_config_lov);
r_layout_config_lov.lov_config_id := hls_util_pkg.format_number(hls_doc_layout_config_lov_s.nextval);r_layout_config_lov.config_id := hls_util_pkg.format_number(v_layout_config_id);r_layout_config_lov.lov_col_for_query := 'Y';r_layout_config_lov.lov_col_for_display := 'Y';r_layout_config_lov.lov_col_display_width := 120;r_layout_config_lov.lov_data_type := 'VARCHAR2';r_layout_config_lov.created_by := 1;r_layout_config_lov.creation_date := to_date('2019-04-01','yyyy-mm-dd');r_layout_config_lov.last_update_date := to_date('2019-04-01','yyyy-mm-dd');r_layout_config_lov.last_updated_by  := 1;r_layout_config_lov.lov_col_prompt := '地址';r_layout_config_lov.lov_col_sequence := 3;r_layout_config_lov.lov_col_name := 'ADDRESS';
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config_lov(r_layout_config_lov);
r_layout_config_lov.lov_config_id := hls_util_pkg.format_number(hls_doc_layout_config_lov_s.nextval);r_layout_config_lov.config_id := hls_util_pkg.format_number(v_layout_config_id);r_layout_config_lov.lov_col_for_query := 'Y';r_layout_config_lov.lov_col_for_display := 'Y';r_layout_config_lov.lov_col_display_width := 120;r_layout_config_lov.lov_data_type := 'VARCHAR2';r_layout_config_lov.created_by := 1;r_layout_config_lov.creation_date := to_date('2019-04-01','yyyy-mm-dd');r_layout_config_lov.last_update_date := to_date('2019-04-01','yyyy-mm-dd');r_layout_config_lov.last_updated_by  := 1;r_layout_config_lov.lov_col_prompt := '库点级别';r_layout_config_lov.lov_col_sequence := 4;r_layout_config_lov.lov_col_name := 'INVENTORY_ADDRESS_LEVEL_N';
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config_lov(r_layout_config_lov);
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_ENTRANCE';r_layout_config.tab_code:='G_WILLMOVE' ;r_layout_config.column_name:='BP_ID';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='N' ;r_layout_config.display_order:=5;r_layout_config.prompt:='经销商ID';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='TEXTFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=130;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config_lov.lov_config_id := hls_util_pkg.format_number(hls_doc_layout_config_lov_s.nextval);r_layout_config_lov.config_id := hls_util_pkg.format_number(v_layout_config_id);r_layout_config_lov.lov_col_for_query := 'Y';r_layout_config_lov.lov_col_for_display := 'Y';r_layout_config_lov.lov_col_display_width := 120;r_layout_config_lov.lov_data_type := 'VARCHAR2';r_layout_config_lov.created_by := 1;r_layout_config_lov.creation_date := to_date('2019-04-01','yyyy-mm-dd');r_layout_config_lov.last_update_date := to_date('2019-04-01','yyyy-mm-dd');r_layout_config_lov.last_updated_by  := 1;r_layout_config_lov.lov_col_prompt := 'VALUE_NAME';r_layout_config_lov.lov_col_sequence := 2;r_layout_config_lov.lov_col_name := 'VALUE_NAME';
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config_lov(r_layout_config_lov);
r_layout_config_lov.lov_config_id := hls_util_pkg.format_number(hls_doc_layout_config_lov_s.nextval);r_layout_config_lov.config_id := hls_util_pkg.format_number(v_layout_config_id);r_layout_config_lov.lov_col_for_query := 'Y';r_layout_config_lov.lov_col_for_display := 'Y';r_layout_config_lov.lov_col_display_width := 120;r_layout_config_lov.lov_data_type := 'VARCHAR2';r_layout_config_lov.created_by := 1;r_layout_config_lov.creation_date := to_date('2019-04-01','yyyy-mm-dd');r_layout_config_lov.last_update_date := to_date('2019-04-01','yyyy-mm-dd');r_layout_config_lov.last_updated_by  := 1;r_layout_config_lov.lov_col_prompt := 'BP_CODE';r_layout_config_lov.lov_col_sequence := 3;r_layout_config_lov.lov_col_name := 'BP_CODE';
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config_lov(r_layout_config_lov);
r_layout_config_lov.lov_config_id := hls_util_pkg.format_number(hls_doc_layout_config_lov_s.nextval);r_layout_config_lov.config_id := hls_util_pkg.format_number(v_layout_config_id);r_layout_config_lov.lov_col_for_query := 'Y';r_layout_config_lov.lov_col_for_display := 'Y';r_layout_config_lov.lov_col_display_width := 120;r_layout_config_lov.lov_data_type := 'NUMBER';r_layout_config_lov.created_by := 1;r_layout_config_lov.creation_date := to_date('2019-04-01','yyyy-mm-dd');r_layout_config_lov.last_update_date := to_date('2019-04-01','yyyy-mm-dd');r_layout_config_lov.last_updated_by  := 1;r_layout_config_lov.lov_col_prompt := 'VALUE_CODE';r_layout_config_lov.lov_col_sequence := 1;r_layout_config_lov.lov_col_name := 'VALUE_CODE';
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config_lov(r_layout_config_lov);
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_ENTRANCE';r_layout_config.tab_code:='G_WILLMOVE' ;r_layout_config.column_name:='BP_NAME';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=6;r_layout_config.prompt:='经销商名称';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='TEXTFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=130;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_ENTRANCE';r_layout_config.tab_code:='G_WILLMOVE' ;r_layout_config.column_name:='CAR_INFO_ID';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='N' ;r_layout_config.display_order:=null;r_layout_config.prompt:=null;r_layout_config.input_mode:=null;r_layout_config.validation_type:='TEXTFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=null;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_ENTRANCE';r_layout_config.tab_code:='G_WILLMOVE' ;r_layout_config.column_name:='CAR_STATUS';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=90;r_layout_config.prompt:='车辆状态';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='COMBOBOX' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=120;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:='select S.code_value value_code,S.code_value_name  VALUE_NAME
  from sys_code_values_v s
 where s.code = ''KR_CAR_STATUS''
   and s.code_enabled_flag = ''Y''
   AND S.code_value_enabled_flag = ''Y''
   ORDER BY S.order_seq';r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_ENTRANCE';r_layout_config.tab_code:='G_WILLMOVE' ;r_layout_config.column_name:='CONTRACT_NUMBER';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=15;r_layout_config.prompt:='合同编号';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='TEXTFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=130;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_ENTRANCE';r_layout_config.tab_code:='G_WILLMOVE' ;r_layout_config.column_name:='CONTRACT_STATUS';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=100;r_layout_config.prompt:='合同状态';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='COMBOBOX' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=120;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:='select S.code_value value_code,S.code_value_name  VALUE_NAME
  from sys_code_values_v s
 where s.code = ''CON660_CONTRACT_STATUS''
   and s.code_enabled_flag = ''Y''
   AND S.code_value_enabled_flag = ''Y''
   ORDER BY S.order_seq';r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_ENTRANCE';r_layout_config.tab_code:='G_WILLMOVE' ;r_layout_config.column_name:='ITEM_ENGINE_NUMBER';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=60;r_layout_config.prompt:='发动机号';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='TEXTFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=120;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_ENTRANCE';r_layout_config.tab_code:='G_WILLMOVE' ;r_layout_config.column_name:='ITEM_FRAME_NUMBER';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=20;r_layout_config.prompt:='VIN码';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='TEXTFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=150;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_ENTRANCE';r_layout_config.tab_code:='G_WILLMOVE' ;r_layout_config.column_name:='MODEL_CODE';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=30;r_layout_config.prompt:='车型代码';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='TEXTFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=130;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_ENTRANCE';r_layout_config.tab_code:='G_WILLMOVE' ;r_layout_config.column_name:='MODEL_CODE_NAME';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=40;r_layout_config.prompt:='车型代码描述';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='TEXTFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=150;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_ENTRANCE';r_layout_config.tab_code:='G_WILLMOVE' ;r_layout_config.column_name:='PROJECT_NUMBER';r_layout_config.data_type:='VARCHAR2';r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=10;r_layout_config.prompt:='申请编号';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='TEXTFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=130;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_ENTRANCE';r_layout_config.tab_code:='G_WILLMOVE' ;r_layout_config.column_name:='QUALIFIED_NUMBER';r_layout_config.data_type:='VARCHAR2';r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=70;r_layout_config.prompt:='合格证号';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='TEXTFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=120;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_ENTRANCE';r_layout_config.tab_code:='G_WILLMOVE' ;r_layout_config.column_name:='SON_CODE';r_layout_config.data_type:='VARCHAR2';r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=16;r_layout_config.prompt:='SON号';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='TEXTFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=130;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_screen(P_LAYOUT_CODE=>'DF_MOVE_CARS_ENTRANCE',P_TAB_CODE=>'F_QUERY',P_ORDER_SEQ=>1,P_COLUMN_NAME=>'PROJECT_NUMBER',P_INPUT_MODE=>'OPTION',P_COLSPAN=>null,P_ROWSPAN=>null,P_HEIGHT=>null,P_USER_ID=>1);
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_screen(P_LAYOUT_CODE=>'DF_MOVE_CARS_ENTRANCE',P_TAB_CODE=>'F_QUERY',P_ORDER_SEQ=>2,P_COLUMN_NAME=>'CONTRACT_NUMBER',P_INPUT_MODE=>'OPTION',P_COLSPAN=>null,P_ROWSPAN=>null,P_HEIGHT=>null,P_USER_ID=>1);
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_screen(P_LAYOUT_CODE=>'DF_MOVE_CARS_ENTRANCE',P_TAB_CODE=>'F_QUERY',P_ORDER_SEQ=>3,P_COLUMN_NAME=>'CONTRACT_STATUS',P_INPUT_MODE=>'OPTION',P_COLSPAN=>null,P_ROWSPAN=>null,P_HEIGHT=>null,P_USER_ID=>1);
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_screen(P_LAYOUT_CODE=>'DF_MOVE_CARS_ENTRANCE',P_TAB_CODE=>'F_QUERY',P_ORDER_SEQ=>4,P_COLUMN_NAME=>'ITEM_FRAME_NUMBER',P_INPUT_MODE=>'OPTION',P_COLSPAN=>null,P_ROWSPAN=>null,P_HEIGHT=>null,P_USER_ID=>1);
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_screen(P_LAYOUT_CODE=>'DF_MOVE_CARS_ENTRANCE',P_TAB_CODE=>'F_QUERY',P_ORDER_SEQ=>5,P_COLUMN_NAME=>'SON_CODE',P_INPUT_MODE=>'OPTION',P_COLSPAN=>null,P_ROWSPAN=>null,P_HEIGHT=>null,P_USER_ID=>1);
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_screen(P_LAYOUT_CODE=>'DF_MOVE_CARS_ENTRANCE',P_TAB_CODE=>'F_QUERY',P_ORDER_SEQ=>6,P_COLUMN_NAME=>'CAR_STATUS',P_INPUT_MODE=>'OPTION',P_COLSPAN=>null,P_ROWSPAN=>null,P_HEIGHT=>null,P_USER_ID=>1);
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_screen(P_LAYOUT_CODE=>'DF_MOVE_CARS_ENTRANCE',P_TAB_CODE=>'F_QUERY',P_ORDER_SEQ=>7,P_COLUMN_NAME=>null,P_INPUT_MODE=>null,P_COLSPAN=>null,P_ROWSPAN=>null,P_HEIGHT=>null,P_USER_ID=>1);
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_screen(P_LAYOUT_CODE=>'DF_MOVE_CARS_ENTRANCE',P_TAB_CODE=>'F_QUERY',P_ORDER_SEQ=>8,P_COLUMN_NAME=>null,P_INPUT_MODE=>null,P_COLSPAN=>null,P_ROWSPAN=>null,P_HEIGHT=>null,P_USER_ID=>1);
END;
/
commit;

set feedback on
set define on

spool off

exit
