WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
WHENEVER OSERROR  EXIT FAILURE ROLLBACK;

spool 20190401_df_move_cars_modify.log

set feedback off
set define off


DECLARE
r_layout_config hls_doc_layout_config%rowtype;
r_layout_config_lov hls_doc_layout_config_lov%rowtype;
v_layout_config_id number;
BEGIN
SYS_LOAD_HLS_DOC_LAYOUT_PKG.delete_layout('DF_MOVE_CARS_MODIFY');
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout(P_LAYOUT_CODE=>'DF_MOVE_CARS_MODIFY',P_DESCRIPTION=>'车辆移库申请维护(DF)',P_DOCUMENT_CATEGORY=>'CONTRACT',P_ORDER_SEQ=>125,P_ENABLED_FLAG=>'Y',P_USER_ID=>1);
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_tab(P_LAYOUT_CODE=>'DF_MOVE_CARS_MODIFY',P_TAB_CODE=>'F_FORM',P_TAB_TYPE=>'FORM',P_TAB_DESC=>'查询条件',P_ENABLED_FLAG=>'Y',P_PARENT_TAB_CODE=>null,P_TAB_SEQ=>10,P_TAB_GROUP=>null,P_BASE_TABLE=>null,P_BASE_TABLE_PK=>null,P_BASE_TABLE_FIELD=>null,P_QUERY_SOURCE=>null,P_PARENT_TABLE=>null,P_CONFIGURABLE=>'Y',P_ROW_COUNT=>1,P_COLUMN_COUNT=>4,P_LABEL_WIDTH=>120,P_FIELD_WIDTH=>150,P_MARGIN_TOP=>3,P_MARGIN_HEIGHT=>100,P_MARGIN_WIDTH=>50,P_SHOW_BOX=>'Y',P_BOX_WIDTH=>1112,P_TREE_CODE=>null,P_TREE_LEVEL=>1,P_REPEAT_OBJECT=>null,P_REF_TAB_CODE=>null,P_TAB_REF_SCREEN=>null,P_REPEAT_BINDERTARGET_FLAG=>'N',P_ROOT_TREE_CODE=>null,P_SETUP_HEIGHT=>'MARGIN_HEIGHT',P_HEIGHT=>null,P_SETUP_WIDTH=>'MARGIN_WIDTH',P_WIDTH=>null,P_PARENT_LOADED_OBJECT=>null,P_ATTACHMENT_TAB_GROUP=>null,P_REPEAT_BINDNAME_OBJECT=>null,P_USER_ID=>1,P_QUERY_ONLY=>'N',P_REF_V01=>null,P_REF_V02=>null,P_REF_V03=>null,P_REF_V04=>null,P_REF_V05=>null,P_FETCHALL =>'N',P_QUERY_TAB_CODE =>null,P_FIELDWIDTH =>null,P_FIELDHEIGHT =>null,P_CHECK_BEFORE_DELETE_BM =>null,P_CHECK_AFTER_SAVE_BM =>null,P_SWITCHCARD_VALUE=>null,P_RECREATE_DS_FLAG=>'N');
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_tab(P_LAYOUT_CODE=>'DF_MOVE_CARS_MODIFY',P_TAB_CODE=>'G_RESULT',P_TAB_TYPE=>'SINGLE_GRID',P_TAB_DESC=>'移库申请',P_ENABLED_FLAG=>'Y',P_PARENT_TAB_CODE=>null,P_TAB_SEQ=>20,P_TAB_GROUP=>null,P_BASE_TABLE=>'CON_MOVE_CARS_HD',P_BASE_TABLE_PK=>'HD_ID',P_BASE_TABLE_FIELD=>null,P_QUERY_SOURCE=>'con_move_cars_hd_lv',P_PARENT_TABLE=>null,P_CONFIGURABLE=>'Y',P_ROW_COUNT=>0,P_COLUMN_COUNT=>4,P_LABEL_WIDTH=>120,P_FIELD_WIDTH=>150,P_MARGIN_TOP=>3,P_MARGIN_HEIGHT=>200,P_MARGIN_WIDTH=>50,P_SHOW_BOX=>'Y',P_BOX_WIDTH=>1112,P_TREE_CODE=>null,P_TREE_LEVEL=>1,P_REPEAT_OBJECT=>null,P_REF_TAB_CODE=>null,P_TAB_REF_SCREEN=>null,P_REPEAT_BINDERTARGET_FLAG=>'N',P_ROOT_TREE_CODE=>null,P_SETUP_HEIGHT=>'MARGIN_HEIGHT',P_HEIGHT=>null,P_SETUP_WIDTH=>'MARGIN_WIDTH',P_WIDTH=>null,P_PARENT_LOADED_OBJECT=>null,P_ATTACHMENT_TAB_GROUP=>null,P_REPEAT_BINDNAME_OBJECT=>null,P_USER_ID=>1,P_QUERY_ONLY=>'N',P_REF_V01=>null,P_REF_V02=>null,P_REF_V03=>null,P_REF_V04=>null,P_REF_V05=>null,P_FETCHALL =>'N',P_QUERY_TAB_CODE =>'F_FORM',P_FIELDWIDTH =>null,P_FIELDHEIGHT =>null,P_CHECK_BEFORE_DELETE_BM =>null,P_CHECK_AFTER_SAVE_BM =>null,P_SWITCHCARD_VALUE=>null,P_RECREATE_DS_FLAG=>'N');
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_MODIFY';r_layout_config.tab_code:='F_FORM' ;r_layout_config.column_name:='CREATED_DATE';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=null;r_layout_config.prompt:='创建日期';r_layout_config.input_mode:=null;r_layout_config.validation_type:='DATEPICKER' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=null;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_MODIFY';r_layout_config.tab_code:='F_FORM' ;r_layout_config.column_name:='DESCRIPTION';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=null;r_layout_config.prompt:='创建者';r_layout_config.input_mode:=null;r_layout_config.validation_type:='TEXTFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=null;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_MODIFY';r_layout_config.tab_code:='F_FORM' ;r_layout_config.column_name:='HD_NUMBER';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=null;r_layout_config.prompt:='移库申请编号';r_layout_config.input_mode:=null;r_layout_config.validation_type:='TEXTFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=null;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_MODIFY';r_layout_config.tab_code:='F_FORM' ;r_layout_config.column_name:='STATUS';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=null;r_layout_config.prompt:='移库申请状态';r_layout_config.input_mode:=null;r_layout_config.validation_type:='COMBOBOX' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=null;r_layout_config.percent:=null;r_layout_config.default_value:='NEW';r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:='Select cv.code_value_name value_name, cv.code_value value_code
          From sys_code_values_v cv
         Where cv.code = ''DF_MOVE_STATUS''
           And cv.code_enabled_flag = ''Y''
           And cv.code_value_enabled_flag = ''Y''';r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_MODIFY';r_layout_config.tab_code:='G_RESULT' ;r_layout_config.column_name:='BP_NAME';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=10;r_layout_config.prompt:='经销商名称';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='TEXTFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=250;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_MODIFY';r_layout_config.tab_code:='G_RESULT' ;r_layout_config.column_name:='CREATED_DATE';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=60;r_layout_config.prompt:='创建日期';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='DATEPICKER' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=null;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_MODIFY';r_layout_config.tab_code:='G_RESULT' ;r_layout_config.column_name:='EARLY_REDEMP_PAYMENT_SUM';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=30;r_layout_config.prompt:='移库保证金总额';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='NUMBERFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=2;r_layout_config.zero_fill:='TRUE';r_layout_config.allow_format:='TRUE';r_layout_config.allow_decimal:='TRUE';r_layout_config.alignment:=null ;r_layout_config.width:=null;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_MODIFY';r_layout_config.tab_code:='G_RESULT' ;r_layout_config.column_name:='HD_NUMBER';r_layout_config.data_type:='VARCHAR2';r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=1;r_layout_config.prompt:='移库申请号';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='LINK' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=180;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_MODIFY';r_layout_config.tab_code:='G_RESULT' ;r_layout_config.column_name:='REDEMP_PAYMENT_SUM';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=20;r_layout_config.prompt:='保理融资额总额';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='NUMBERFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=2;r_layout_config.zero_fill:='TRUE';r_layout_config.allow_format:='TRUE';r_layout_config.allow_decimal:='TRUE';r_layout_config.alignment:=null ;r_layout_config.width:=null;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_MODIFY';r_layout_config.tab_code:='G_RESULT' ;r_layout_config.column_name:='STATUS';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=40;r_layout_config.prompt:='移库申请状态';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='COMBOBOX' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=null;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:='Select cv.code_value_name value_name, cv.code_value value_code
          From sys_code_values_v cv
         Where cv.code = ''DF_MOVE_STATUS''
           And cv.code_enabled_flag = ''Y''
           And cv.code_value_enabled_flag = ''Y''';r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='DF_MOVE_CARS_MODIFY';r_layout_config.tab_code:='G_RESULT' ;r_layout_config.column_name:='USER_ID_N';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=50;r_layout_config.prompt:='创建者';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='TEXTFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=200;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-04-01','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_screen(P_LAYOUT_CODE=>'DF_MOVE_CARS_MODIFY',P_TAB_CODE=>'F_FORM',P_ORDER_SEQ=>1,P_COLUMN_NAME=>'HD_NUMBER',P_INPUT_MODE=>null,P_COLSPAN=>null,P_ROWSPAN=>null,P_HEIGHT=>null,P_USER_ID=>1);
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_screen(P_LAYOUT_CODE=>'DF_MOVE_CARS_MODIFY',P_TAB_CODE=>'F_FORM',P_ORDER_SEQ=>2,P_COLUMN_NAME=>'STATUS',P_INPUT_MODE=>null,P_COLSPAN=>null,P_ROWSPAN=>null,P_HEIGHT=>null,P_USER_ID=>1);
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_screen(P_LAYOUT_CODE=>'DF_MOVE_CARS_MODIFY',P_TAB_CODE=>'F_FORM',P_ORDER_SEQ=>3,P_COLUMN_NAME=>'DESCRIPTION',P_INPUT_MODE=>null,P_COLSPAN=>null,P_ROWSPAN=>null,P_HEIGHT=>null,P_USER_ID=>1);
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_screen(P_LAYOUT_CODE=>'DF_MOVE_CARS_MODIFY',P_TAB_CODE=>'F_FORM',P_ORDER_SEQ=>4,P_COLUMN_NAME=>'CREATED_DATE',P_INPUT_MODE=>null,P_COLSPAN=>null,P_ROWSPAN=>null,P_HEIGHT=>null,P_USER_ID=>1);
END;
/
commit;

set feedback on
set define on

spool off

exit
