var enableLayoutConfig = {
	'modules/layout/layout_test.screen' : true,
	'modules/psr/PSR1020/psr_report_parameter_dynamic.screen' : true,
	'modules/prj/PRJ400N/prj_chance_create_entrance.screen' : true,
	'modules/prj/PRJ400N/prj_chance_create.screen' : true,
	'modules/prj/PRJ401N/prj_chance_modify_entrance.screen' : true,
	'modules/prj/PRJ401N/prj_chance_modify.screen' : true,
	'modules/cont/CON501N/con_contract_modify_entrance.screen' : true,
	'modules/cont/CON501N/con_contract_modify.screen' : true,
	'modules/hls/HLS202N/hls_lease_item_create_entrace.screen' : true,
	'modules/prj/PRJ501N/prj_project_modify_entrance.screen' : true,
	'modules/prj/PRJ501N/prj_project_modify.screen' : true,
	'modules/hls/HLS214N/hls_bp_master_modify_entrance.screen' : true,
	'modules/hls/HLS214N/hls_bp_master_modify.screen' : true,
	'modules/cont/CON301N/con_contract_query_entrance.screen' : true,
	'modules/hls/HLS217N/hls_mortgage_modify_entrance.screen' : true,
	'modules/hls/HLS217N/hls_mortgage_modify.screen' : true,
	'modules/hls/HLS203N/hls_lease_item_modify_entrance.screen' : true,
	'modules/hls/HLS203N/hls_lease_item_modify.screen' : true,
	'modules/hls/HLS030N/hls_doc_layout_preview.screen' : true,
	'modules/hls/HLS202N/hls_lease_item_create_entrance.screen' : true,
	'modules/hls/HLS202N/hls_lease_item_create.screen' : true,
	'modules/hls/HLS216N/hls_mortgage_create_entrance.screen' : true,
	'modules/hls/HLS216N/hls_mortgage_create.screen' : true,
	'modules/hls/HLS213N/hls_bp_master_create.screen' : true,
	'modules/hls/HLS213N/hls_bp_master_create_entrance.screen' : true,
	'modules/prj/PRJ501N/prj_project_create_screen_n.screen' : true,
	'modules/prj/PRJ501N/prj_project_create_tree_detail_include_n.screen' : true,
	'modules/csh/CSH710N/csh_deduction_entrance.screen' :true,
	'modules/prj/PRJ500N/prj_project_create_entrance.screen' :true,
	'modules/prj/PRJ500N/prj_project_create.screen':true,
	'modules/prj/PRJ501N/prj_project_maintain.screen':true,
	'modules/prj/PRJ500N/prj_project_create_manager.screen':true,
	'modules/cont/CON731/hls_ccrg_create_entrance.screen':true,
	'modules/cont/CON731/hls_con_contract_change_entrance.screen':true,
	'modules/cont/CON731/hls_con_contract_change_detail.screen':true,
	'modules/cont/CON732/hls_ccr_modify_entrance.screen':true,
	'modules/zjwfl/ZJWFL1060/zj_wfl_monitoring_node_approve_history.screen':true,
	'modules/zjwfl/ZJWFL5110/zj_wfl_approve.screen' : true,
	'modules/prj/PRJ501N/prj_project_maintain_manager.screen':true,
	'modules/prj/PRJ502N/prj_project_modify_entrance.screen':true,
	'modules/cont/CON501N/hls_bp_master_modify.screen':true,
	'modules/cont/CON505/con_contract_modify.screen':true,
	'modules/cont/CON505/hls_bp_master_query.screen':true,
	'modules/zjwfl/ZJWFL3010/zj_wfl_approve_history_for_submitter.screen':true,
	'modules/hls/HLS215N/hls_bp_master_query.screen':true,
	'modules/cont/CON504/con_contract_modify.screen':true,
	'modules/prj/PRJ500N/prj_project_create_special.screen':true,
	'modules/cont/CON504/con_contract_query.screen':true,
	'modules/cont/CON505/con_contract_query.screen':true,
	'modules/zjwfl/ZJWFL3040/zj_wfl_my_approved_application_history.screen':true,
	'modules/prj/PRJ600/prj_project_maintain_entrance.screen':true,
	'modules/cont/CON501N/con_item_detail_maintain.screen':true,
	'modules/cont/CON501N/con_item_detail_query.screen':true,
	'modules/cont/CON501P/con_contract_modify_prj_entrance.screen':true,
	'modules/hls/HLS215N/hls_bp_master_query_entrance.screen':true,
	'modules/cont/CON501P/con_contract_prj_modify.screen':true,
	'modules/cont/CON504P/con_contract_query.screen':true,
	'modules/prj/PRJ504N/prj_project_create_entrance.screen':true,
	'modules/hls/HLS213N/hls_bp_master_entrance_con.screen':true,
	'modules/hls/HLS213N/hls_bp_master_create_con_change.screen':true,
	'modules/cont/CON302/con_contract_query_entrance_inter.screen':true,
	'modules/csh/CSH501/csh_payment_req.screen':true,
	'modules/cont/CON509/con_contract_location.screen' :true,
	'modules/ast/AST503/ast_con_insurance_detail.screen':true,
	'modules/cont/CON704/con_extension_detail.screen':true,
	'modules/wfl_screen/CON_CONTRACT/con_contract_change_req_dynamic_for_wfl.screen':true,
	'modules/cont/CON501N/con_contract_modify_query.screen':true,
	'modules/ebank/EBANK110/ebk_ws_xmltpl_define.screen':true,
	'modules/ebank/EBANK_CSH111/ebank_spd_pub_maintain.screen':true,
	'modules/cont/CON632/con_collection_maintain_detail.screen':true,
	'modules/cont/CON631/collection_overdue_status.screen':true,
	'modules/cont/CON632V/con632v_visit_wfl.screen':true,
	'modules/cont/CON632C/con632_letter_wfl.screen':true,
	'modules/cont/CON632L/con_letter_law_wfl.screen':true,
	'modules/cont/CON753/con_contract_change_in.screen':true,
	'modules/cont/CON753/con_contract_change_in_detail.screen':true,
	'modules/cont/CON636/con_collection_last.screen':true,
	'modules/cont/CON636/con_collection_last_detail.screen':true,
	'modules/cont/CON636/con_collection_last.screen':true,
	'modules/hls/HLS214N/hls_bp_master_modify_entrance_test.screen':true,
	'modules/ccb/ccb_request_format_definition.screen':true,
	'modules/sap/hls_sys_sap_account_attr_sets.screen':true,
	'modules/hls/HLS051/hls_product_plan_defintion.screen':true,
	'modules/hls/HLS051/hls_product_no_gps_condition.screen':true,
	'modules/hls/HLS051/hls_plan_to_grant.screen':true,
	'modules/hls/HLS051/hls_product_car_discount.screen':true,
	'modules/hls/HLS218/hls_lease_products.screen':true,
	'modules/hls/HLS051/hls_product_car_dis.screen':true,
	'modules/prj/PRJ501N/prj_analyse_detail.screen':true,
	'modules/zx/ZX5010/hls_zx_post.screen':true,
	'modules/prj/PRJ501N/prj_project_maintain_readonly.screen':true,
	'modules/hls_acr/HLS_ACR5030/hls_acr_ebank_input.screen':true,
	'modules/ccb/ccb301/ebank_ccb_transaction.screen':true,
	'modules/csh/CSH570/risk_entrance.screen':true,
	'modules/csh/CSH711/csh_deduction_reverse_entrance.screen':true,
	'modules/ccb/ccb501/ccb_manual_cashflow.screen':true,
	'modules/ccb/ccb502/ccb_manual_transaction_create.screen':true,
	'modules/csh/CSH711/csh_deduction_reverse_entrance.screen':true,
	'modules/csh/CSH720/discount_amount_list.screen':true,
	'modules/csh/CSH730/service_amount_list.screen':true,
	'modules/hls/HLS1004/hls_notice_defintion.screen':true,
	'modules/csh/CSH740/discount_query.screen':true,
	'modules/prj/PRJ503/prj_project_return_entrance.screen':true,
	'modules/zx/ZX5020/hls_zx_query.screen':true,
	'modules/prj/PRJ506/prj_project_reject_entrance.screen':true,
	'modules/zx/ZX5020/hls_zx_query.screen':true,
	'modules/csh/CSH560/vender_deposit_return.screen':true,
	'modules/cont/CON590/con_contract_report.screen':true,
	'modules/cont/CON600/con_contract_overdue_query.screen':true,
	'modules/prj/PRJ502/prj_project_inquire.screen':true,
	'modules/cont/CON542/con_contract_cancel_maintain.screen':true,
	'modules/cont/CON570/con_contract_content_query.screen':true,
	'modules/cont/CON540/con_contract_cancel_maintain_query.screen':true,
	'modules/hls/hls_comment_report.screen':true,
	'modules/cont/CON575/con_contract_content_query.screen':true,
	'modules/cont/CON733/hls_con_contract_et_create_entrance.screen':true,
	'modules/cont/CON920/basic_data.screen':true,
	'modules/csh/CSH507/csh_pay_ccb_list.screen':true,
	'modules/acr/ACR310/acr_invoice_query.screen':true,
	'modules/cont/CON520/con_pay.screen':true,
	'modules/csh/CSH525/con_agent_pay.screen':true,
	'modules/csh/CSH526/con_income.screen':true,
	'modules/csh/CSH527/ebank_fail.screen':true,
	'modules/acr/ACR310/acr_invoice_query.screen':true,
	'modules/psbc/psbc301/ebank_psbc_transaction.screen':true,
	'modules/ccb/ccb305/ebank_document_detail.screen':true,
	'modules/cont/CON521/con_income_detail.screen':true,
	'modules/ebank/EBANK001/ebk_withhold_bank_definition.screen':true,
	'modules/csh/CSH531/agent_pay_rank.screen':true,
	'modules/ebank/EBANK001/ebk_withhold_bank_definition.screen':true,
	'modules/csh/CSH534/csh_write_off_query.screen':true,
	'modules/csh/CSH532/outposted_performance.screen':true,
	'modules/prj/PRJ507/hls_calc_estimate.screen':true,
	'modules/csh/CSH537/agent_finance_rank.screen':true,
	'modules/csh/CSH501/csh_payment_req_bond.screen':true,
	'modules/cont/CON522/con_asset.screen':true,
	'modules/csh/CSH501/csh_payment_req_bond.screen':true,
	'modules/csh/CSH535/cwo_balance.screen':true,
	'modules/csh/CSH538/income_stat.screen':true,
	'modules/hls/HLS330/agent_contact_data.screen':true,
	'modules/cont/CON523/special_con_query.screen':true,
	'modules/csh/CSH539/account_query.screen':true,
	'modules/cont/CON761/con_contract_terminate.screen':true,
	'modules/ebank/EBANK100/hls_sap_bank.screen':true,
	'modules/ebank/EBANK101/hls_sap_city.screen':true,
	'modules/cont/CON762/con_contract_finish_query.screen':true,
	'modules/csh/CSH540/agent_deposit_return.screen':true,
	'modules/hls/HLS530/manual_journal_create.screen':true,
	'modules/csh/CSH541/agent_deposit_details.screen':true,
	'modules/hls/HLS535/hls_sap_process_resend.screen':true,
	'modules/prj/PRJ500/prj_project_create_entrance.screen':true,
	'modules/prj/PRJ500/prj_project_create.screen':true,
	'modules/csh/CSH541/agent_deposit_details.screen':true,
	'modules/cont/CON311/con_re_print_entrance.screen':true,
	'modules/cont/CON311/con_re_print_modify.screen':true,
	'modules/csh/CSH508/hls_bpm_interface.screen':true,
	'modules/prj/PRJ600/prj_project_maintain_entrance.screen':true,
	'modules/prj/PRJ600/prj_project_maintain.screen':true,
	'modules/cont/CON501N/eq_con_contract_modify50.screen':true,
	'modules/cont/CON517/con_cashlfows_entrance.screen':true,
	'modules/cont/CON517/con_cashflows_details.screen':true,
	'modules/cre/CRE000/credit_query_maintain.screen':true,
	'modules/cre/CRE000/credit_query_request.screen':true,
	'modules/cre/CRE000/credit_query_detail.screen':true
	
};