WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
WHENEVER OSERROR  EXIT FAILURE ROLLBACK;

spool 20190228_factoring_management_fee_state.log

set feedback off
set define off


DECLARE
r_layout_config hls_doc_layout_config%rowtype;
r_layout_config_lov hls_doc_layout_config_lov%rowtype;
v_layout_config_id number;
BEGIN
SYS_LOAD_HLS_DOC_LAYOUT_PKG.delete_layout('FACTORING_MANAGEMENT_FEE_STATE');
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout(P_LAYOUT_CODE=>'FACTORING_MANAGEMENT_FEE_STATE',P_DESCRIPTION=>'保理管理费结算单',P_DOCUMENT_CATEGORY=>'CONTRACT',P_ORDER_SEQ=>null,P_ENABLED_FLAG=>'Y',P_USER_ID=>1);
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_tab(P_LAYOUT_CODE=>'FACTORING_MANAGEMENT_FEE_STATE',P_TAB_CODE=>'F_QUERY',P_TAB_TYPE=>'FORM',P_TAB_DESC=>'查询条件',P_ENABLED_FLAG=>'Y',P_PARENT_TAB_CODE=>null,P_TAB_SEQ=>10,P_TAB_GROUP=>null,P_BASE_TABLE=>null,P_BASE_TABLE_PK=>null,P_BASE_TABLE_FIELD=>null,P_QUERY_SOURCE=>null,P_PARENT_TABLE=>null,P_CONFIGURABLE=>'Y',P_ROW_COUNT=>1,P_COLUMN_COUNT=>3,P_LABEL_WIDTH=>120,P_FIELD_WIDTH=>150,P_MARGIN_TOP=>3,P_MARGIN_HEIGHT=>100,P_MARGIN_WIDTH=>50,P_SHOW_BOX=>'Y',P_BOX_WIDTH=>1112,P_TREE_CODE=>null,P_TREE_LEVEL=>1,P_REPEAT_OBJECT=>null,P_REF_TAB_CODE=>null,P_TAB_REF_SCREEN=>null,P_REPEAT_BINDERTARGET_FLAG=>'N',P_ROOT_TREE_CODE=>null,P_SETUP_HEIGHT=>'MARGIN_HEIGHT',P_HEIGHT=>null,P_SETUP_WIDTH=>'MARGIN_WIDTH',P_WIDTH=>null,P_PARENT_LOADED_OBJECT=>null,P_ATTACHMENT_TAB_GROUP=>null,P_REPEAT_BINDNAME_OBJECT=>null,P_USER_ID=>1,P_QUERY_ONLY=>'N',P_REF_V01=>null,P_REF_V02=>null,P_REF_V03=>null,P_REF_V04=>null,P_REF_V05=>null,P_FETCHALL =>'N',P_QUERY_TAB_CODE =>null,P_FIELDWIDTH =>null,P_FIELDHEIGHT =>null,P_CHECK_BEFORE_DELETE_BM =>null,P_CHECK_AFTER_SAVE_BM =>null,P_SWITCHCARD_VALUE=>null,P_RECREATE_DS_FLAG=>'N');
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_tab(P_LAYOUT_CODE=>'FACTORING_MANAGEMENT_FEE_STATE',P_TAB_CODE=>'G_RESULTS',P_TAB_TYPE=>'SINGLE_GRID',P_TAB_DESC=>null,P_ENABLED_FLAG=>'Y',P_PARENT_TAB_CODE=>null,P_TAB_SEQ=>20,P_TAB_GROUP=>null,P_BASE_TABLE=>'CON_CONTRACT',P_BASE_TABLE_PK=>'CONTRACT_ID',P_BASE_TABLE_FIELD=>null,P_QUERY_SOURCE=>'FACTORING_MANAGEMENT_FEE_LV',P_PARENT_TABLE=>null,P_CONFIGURABLE=>'Y',P_ROW_COUNT=>0,P_COLUMN_COUNT=>4,P_LABEL_WIDTH=>120,P_FIELD_WIDTH=>150,P_MARGIN_TOP=>3,P_MARGIN_HEIGHT=>100,P_MARGIN_WIDTH=>50,P_SHOW_BOX=>'Y',P_BOX_WIDTH=>1112,P_TREE_CODE=>null,P_TREE_LEVEL=>1,P_REPEAT_OBJECT=>null,P_REF_TAB_CODE=>null,P_TAB_REF_SCREEN=>null,P_REPEAT_BINDERTARGET_FLAG=>'N',P_ROOT_TREE_CODE=>null,P_SETUP_HEIGHT=>'MARGIN_HEIGHT',P_HEIGHT=>null,P_SETUP_WIDTH=>'MARGIN_WIDTH',P_WIDTH=>null,P_PARENT_LOADED_OBJECT=>null,P_ATTACHMENT_TAB_GROUP=>null,P_REPEAT_BINDNAME_OBJECT=>null,P_USER_ID=>1,P_QUERY_ONLY=>'N',P_REF_V01=>null,P_REF_V02=>null,P_REF_V03=>null,P_REF_V04=>null,P_REF_V05=>null,P_FETCHALL =>'N',P_QUERY_TAB_CODE =>'F_QUERY',P_FIELDWIDTH =>null,P_FIELDHEIGHT =>null,P_CHECK_BEFORE_DELETE_BM =>null,P_CHECK_AFTER_SAVE_BM =>null,P_SWITCHCARD_VALUE=>null,P_RECREATE_DS_FLAG=>'N');
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='FACTORING_MANAGEMENT_FEE_STATE';r_layout_config.tab_code:='F_QUERY' ;r_layout_config.column_name:='BP_ID';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=null;r_layout_config.prompt:='经销商';r_layout_config.input_mode:=null;r_layout_config.validation_type:='LOV_D' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=null;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:='select hbm.bp_id value_code, hbm.bp_name value_name, hbm.bp_code
  from hls_bp_master hbm
 where hbm.enabled_flag = ''Y''
   and hbm.bp_category = ''AGENT''
   and bp_id =nvl((select bp_id
                        from sys_user
                        where user_id =${/session/@user_id}),bp_id)';r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-02-28','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-02-28','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config_lov.lov_config_id := hls_util_pkg.format_number(hls_doc_layout_config_lov_s.nextval);r_layout_config_lov.config_id := hls_util_pkg.format_number(v_layout_config_id);r_layout_config_lov.lov_col_for_query := 'N';r_layout_config_lov.lov_col_for_display := 'N';r_layout_config_lov.lov_col_display_width := 120;r_layout_config_lov.lov_data_type := 'NUMBER';r_layout_config_lov.created_by := 1;r_layout_config_lov.creation_date := to_date('2019-02-28','yyyy-mm-dd');r_layout_config_lov.last_update_date := to_date('2019-02-28','yyyy-mm-dd');r_layout_config_lov.last_updated_by  := 1;r_layout_config_lov.lov_col_prompt := 'VALUE_CODE';r_layout_config_lov.lov_col_sequence := 1;r_layout_config_lov.lov_col_name := 'VALUE_CODE';
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config_lov(r_layout_config_lov);
r_layout_config_lov.lov_config_id := hls_util_pkg.format_number(hls_doc_layout_config_lov_s.nextval);r_layout_config_lov.config_id := hls_util_pkg.format_number(v_layout_config_id);r_layout_config_lov.lov_col_for_query := 'Y';r_layout_config_lov.lov_col_for_display := 'Y';r_layout_config_lov.lov_col_display_width := 120;r_layout_config_lov.lov_data_type := 'VARCHAR2';r_layout_config_lov.created_by := 1;r_layout_config_lov.creation_date := to_date('2019-02-28','yyyy-mm-dd');r_layout_config_lov.last_update_date := to_date('2019-02-28','yyyy-mm-dd');r_layout_config_lov.last_updated_by  := 1;r_layout_config_lov.lov_col_prompt := '经销商名称';r_layout_config_lov.lov_col_sequence := 2;r_layout_config_lov.lov_col_name := 'VALUE_NAME';
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config_lov(r_layout_config_lov);
r_layout_config_lov.lov_config_id := hls_util_pkg.format_number(hls_doc_layout_config_lov_s.nextval);r_layout_config_lov.config_id := hls_util_pkg.format_number(v_layout_config_id);r_layout_config_lov.lov_col_for_query := 'Y';r_layout_config_lov.lov_col_for_display := 'Y';r_layout_config_lov.lov_col_display_width := 120;r_layout_config_lov.lov_data_type := 'VARCHAR2';r_layout_config_lov.created_by := 1;r_layout_config_lov.creation_date := to_date('2019-02-28','yyyy-mm-dd');r_layout_config_lov.last_update_date := to_date('2019-02-28','yyyy-mm-dd');r_layout_config_lov.last_updated_by  := 1;r_layout_config_lov.lov_col_prompt := '经销商编码';r_layout_config_lov.lov_col_sequence := 3;r_layout_config_lov.lov_col_name := 'BP_CODE';
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config_lov(r_layout_config_lov);
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='FACTORING_MANAGEMENT_FEE_STATE';r_layout_config.tab_code:='F_QUERY' ;r_layout_config.column_name:='DATE_FROM';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=null;r_layout_config.prompt:='基准月从';r_layout_config.input_mode:=null;r_layout_config.validation_type:='COMBOBOX' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=null;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:='SELECT
                    internal_period_num value_code,
                    period_name value_name
                FROM
                    gld_period_all_v
                WHERE
                    adjustment_flag=''N'' AND
                    start_date BETWEEN to_date(''2015-01-01'',''YYYY-MM-DD'') AND add_months(sysdate,15)';r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-02-28','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-02-28','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='FACTORING_MANAGEMENT_FEE_STATE';r_layout_config.tab_code:='F_QUERY' ;r_layout_config.column_name:='DATE_TO';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=null;r_layout_config.prompt:='基准月到';r_layout_config.input_mode:=null;r_layout_config.validation_type:='COMBOBOX' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=null;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:='SELECT
                    internal_period_num value_code,
                    period_name value_name
                FROM
                    gld_period_all_v
                WHERE
                    adjustment_flag=''N'' AND
                    start_date BETWEEN to_date(''2015-01-01'',''YYYY-MM-DD'') AND add_months(sysdate,15)';r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-02-28','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-02-28','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='FACTORING_MANAGEMENT_FEE_STATE';r_layout_config.tab_code:='G_RESULTS' ;r_layout_config.column_name:='BP_ID_TENANT_NAME';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=10;r_layout_config.prompt:='经销商名称';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='TEXTFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=null;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-02-28','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-02-28','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='FACTORING_MANAGEMENT_FEE_STATE';r_layout_config.tab_code:='G_RESULTS' ;r_layout_config.column_name:='DUE_AMOUNT';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=130;r_layout_config.prompt:='管理费';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='NUMBERFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=2;r_layout_config.zero_fill:='TRUE';r_layout_config.allow_format:='TRUE';r_layout_config.allow_decimal:='TRUE';r_layout_config.alignment:='RIGHT' ;r_layout_config.width:=null;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-02-28','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-02-28','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='FACTORING_MANAGEMENT_FEE_STATE';r_layout_config.tab_code:='G_RESULTS' ;r_layout_config.column_name:='FACTORING_RESIDUAL';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=140;r_layout_config.prompt:='保理残值';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='NUMBERFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=2;r_layout_config.zero_fill:='TRUE';r_layout_config.allow_format:='TRUE';r_layout_config.allow_decimal:='TRUE';r_layout_config.alignment:='RIGHT' ;r_layout_config.width:=null;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-02-28','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-02-28','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='FACTORING_MANAGEMENT_FEE_STATE';r_layout_config.tab_code:='G_RESULTS' ;r_layout_config.column_name:='FEE_RATE';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=80;r_layout_config.prompt:='管理费率';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='PERCENTFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=2;r_layout_config.zero_fill:='TRUE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='TRUE';r_layout_config.alignment:=null ;r_layout_config.width:=60;r_layout_config.percent:='%';r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-02-28','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-02-28','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='FACTORING_MANAGEMENT_FEE_STATE';r_layout_config.tab_code:='G_RESULTS' ;r_layout_config.column_name:='ITEM_FRAME_NUMBER';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=60;r_layout_config.prompt:='VIN码';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='TEXTFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=null;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-02-28','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-02-28','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='FACTORING_MANAGEMENT_FEE_STATE';r_layout_config.tab_code:='G_RESULTS' ;r_layout_config.column_name:='LAST_RECEIVED_DATE';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=90;r_layout_config.prompt:='赎证日期';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='DATEPICKER' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=80;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-02-28','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-02-28','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='FACTORING_MANAGEMENT_FEE_STATE';r_layout_config.tab_code:='G_RESULTS' ;r_layout_config.column_name:='LEASE_START_DATE';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=40;r_layout_config.prompt:='起息日';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='DATEPICKER' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=80;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-02-28','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-02-28','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='FACTORING_MANAGEMENT_FEE_STATE';r_layout_config.tab_code:='G_RESULTS' ;r_layout_config.column_name:='MODEL_CODE_NAME';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=50;r_layout_config.prompt:='车型';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='TEXTFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=null;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-02-28','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-02-28','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='FACTORING_MANAGEMENT_FEE_STATE';r_layout_config.tab_code:='G_RESULTS' ;r_layout_config.column_name:='PROJECT_NAME';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=25;r_layout_config.prompt:='申请名称';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='TEXTFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=null;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-02-28','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-02-28','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='FACTORING_MANAGEMENT_FEE_STATE';r_layout_config.tab_code:='G_RESULTS' ;r_layout_config.column_name:='PROJECT_NUMBER';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=20;r_layout_config.prompt:='申请编号';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='TEXTFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=null;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-02-28','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-02-28','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='FACTORING_MANAGEMENT_FEE_STATE';r_layout_config.tab_code:='G_RESULTS' ;r_layout_config.column_name:='RECEIVED_AMOUNT';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=70;r_layout_config.prompt:='赎证款';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='NUMBERFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=2;r_layout_config.zero_fill:='TRUE';r_layout_config.allow_format:='TRUE';r_layout_config.allow_decimal:='TRUE';r_layout_config.alignment:='RIGHT' ;r_layout_config.width:=null;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-02-28','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-02-28','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='FACTORING_MANAGEMENT_FEE_STATE';r_layout_config.tab_code:='G_RESULTS' ;r_layout_config.column_name:='SUBMIT_DATE';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=30;r_layout_config.prompt:='申请日期';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='DATEPICKER' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=80;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-02-28','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-02-28','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='FACTORING_MANAGEMENT_FEE_STATE';r_layout_config.tab_code:='G_RESULTS' ;r_layout_config.column_name:='USE_DAYS';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=120;r_layout_config.prompt:='使用日期';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='NUMBERFIELD' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=50;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-02-28','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-02-28','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='FACTORING_MANAGEMENT_FEE_STATE';r_layout_config.tab_code:='G_RESULTS' ;r_layout_config.column_name:='VALID_DATE_FROM';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=100;r_layout_config.prompt:='起始日';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='DATEPICKER' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=80;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-02-28','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-02-28','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
r_layout_config.config_id:=hls_util_pkg.format_number(hls_doc_layout_config_s.nextval) ;r_layout_config.layout_code:='FACTORING_MANAGEMENT_FEE_STATE';r_layout_config.tab_code:='G_RESULTS' ;r_layout_config.column_name:='VALID_DATE_TO';r_layout_config.data_type:=null;r_layout_config.system_flag:='N';r_layout_config.key_field_flag:='N';r_layout_config.enabled_flag:='Y';r_layout_config.display_flag:='Y' ;r_layout_config.display_order:=110;r_layout_config.prompt:='计算期间';r_layout_config.input_mode:='READONLY';r_layout_config.validation_type:='DATEPICKER' ;r_layout_config.validation_sql:=null;r_layout_config.lov_return_vcode:='N';r_layout_config.precision:=null;r_layout_config.zero_fill:='FALSE';r_layout_config.allow_format:='FALSE';r_layout_config.allow_decimal:='FALSE';r_layout_config.alignment:=null ;r_layout_config.width:=80;r_layout_config.percent:=null;r_layout_config.default_value:=null;r_layout_config.upper_limit:=null;r_layout_config.lower_limit:=null;r_layout_config.copy_from_parent_tab:='N';r_layout_config.height:=null;r_layout_config.lov_height:=null;r_layout_config.lov_width:=null;r_layout_config.footerrenderer:='N' ;r_layout_config.lov_cascade_para1:=null;r_layout_config.lov_cascade_para2:=null ;r_layout_config.lov_cascade_para3:=null;r_layout_config.underline:='N';r_layout_config.field_group:=null;r_layout_config.switchcard_tab_code:=null;r_layout_config.base_tab_code:=null;r_layout_config.clob_validation_sql:=null;r_layout_config.field_javascript:=null;r_layout_config.field_bak_flag:='N';r_layout_config.created_by:=1;r_layout_config.last_updated_by:=1;r_layout_config.creation_date:=to_date('2019-02-28','yyyy-mm-dd');r_layout_config.last_update_date:=to_date('2019-02-28','yyyy-mm-dd');r_layout_config.ignore_required := null;SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_config(r_layout_config);
v_layout_config_id := r_layout_config.config_id;
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_screen(P_LAYOUT_CODE=>'FACTORING_MANAGEMENT_FEE_STATE',P_TAB_CODE=>'F_QUERY',P_ORDER_SEQ=>1,P_COLUMN_NAME=>'BP_ID',P_INPUT_MODE=>null,P_COLSPAN=>null,P_ROWSPAN=>null,P_HEIGHT=>null,P_USER_ID=>1);
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_screen(P_LAYOUT_CODE=>'FACTORING_MANAGEMENT_FEE_STATE',P_TAB_CODE=>'F_QUERY',P_ORDER_SEQ=>2,P_COLUMN_NAME=>'DATE_FROM',P_INPUT_MODE=>null,P_COLSPAN=>null,P_ROWSPAN=>null,P_HEIGHT=>null,P_USER_ID=>1);
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_screen(P_LAYOUT_CODE=>'FACTORING_MANAGEMENT_FEE_STATE',P_TAB_CODE=>'F_QUERY',P_ORDER_SEQ=>3,P_COLUMN_NAME=>'DATE_TO',P_INPUT_MODE=>null,P_COLSPAN=>null,P_ROWSPAN=>null,P_HEIGHT=>null,P_USER_ID=>1);
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_tab_button(P_FUNCTION_CODE=>'CSH763',P_LAYOUT_CODE=>'FACTORING_MANAGEMENT_FEE_STATE',P_TAB_CODE=>'G_RESULTS',P_BUTTON_CODE=>'USER_BUTTON4',P_PROMPT=>'用户按钮4',P_SAVE_DATA_FIRST=>'N',P_SYSTEM_FLAG=>'N',P_DISPLAY_FLAG=>'N',P_DISPLAY_ORDER=>130,P_JAVASCRIPT=>null,P_ENABLED_FLAG=>'N',P_USER_ID=>1);
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_tab_button(P_FUNCTION_CODE=>'CSH763',P_LAYOUT_CODE=>'FACTORING_MANAGEMENT_FEE_STATE',P_TAB_CODE=>'G_RESULTS',P_BUTTON_CODE=>'USER_BUTTON5',P_PROMPT=>'用户按钮5',P_SAVE_DATA_FIRST=>'N',P_SYSTEM_FLAG=>'N',P_DISPLAY_FLAG=>'N',P_DISPLAY_ORDER=>140,P_JAVASCRIPT=>null,P_ENABLED_FLAG=>'N',P_USER_ID=>1);
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_tab_button(P_FUNCTION_CODE=>'CSH763',P_LAYOUT_CODE=>'FACTORING_MANAGEMENT_FEE_STATE',P_TAB_CODE=>'G_RESULTS',P_BUTTON_CODE=>'USER_BUTTON6',P_PROMPT=>'用户按钮6',P_SAVE_DATA_FIRST=>'N',P_SYSTEM_FLAG=>'N',P_DISPLAY_FLAG=>'N',P_DISPLAY_ORDER=>150,P_JAVASCRIPT=>null,P_ENABLED_FLAG=>'N',P_USER_ID=>1);
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_tab_button(P_FUNCTION_CODE=>'CSH763',P_LAYOUT_CODE=>'FACTORING_MANAGEMENT_FEE_STATE',P_TAB_CODE=>'G_RESULTS',P_BUTTON_CODE=>'USER_BUTTON7',P_PROMPT=>'用户按钮7',P_SAVE_DATA_FIRST=>'N',P_SYSTEM_FLAG=>'N',P_DISPLAY_FLAG=>'N',P_DISPLAY_ORDER=>160,P_JAVASCRIPT=>null,P_ENABLED_FLAG=>'N',P_USER_ID=>1);
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_tab_button(P_FUNCTION_CODE=>'CSH763',P_LAYOUT_CODE=>'FACTORING_MANAGEMENT_FEE_STATE',P_TAB_CODE=>'G_RESULTS',P_BUTTON_CODE=>'USER_BUTTON8',P_PROMPT=>'用户按钮8',P_SAVE_DATA_FIRST=>'N',P_SYSTEM_FLAG=>'N',P_DISPLAY_FLAG=>'N',P_DISPLAY_ORDER=>170,P_JAVASCRIPT=>null,P_ENABLED_FLAG=>'N',P_USER_ID=>1);
SYS_LOAD_HLS_DOC_LAYOUT_PKG.load_layout_tab_button(P_FUNCTION_CODE=>'CSH763',P_LAYOUT_CODE=>'FACTORING_MANAGEMENT_FEE_STATE',P_TAB_CODE=>'G_RESULTS',P_BUTTON_CODE=>'USER_BUTTON9',P_PROMPT=>'用户按钮9',P_SAVE_DATA_FIRST=>'N',P_SYSTEM_FLAG=>'N',P_DISPLAY_FLAG=>'N',P_DISPLAY_ORDER=>180,P_JAVASCRIPT=>null,P_ENABLED_FLAG=>'N',P_USER_ID=>1);
END;
/
commit;

set feedback on
set define on

spool off

exit
